### ISSUE TITLE
This version of µWS is not compatible with your Node.js build:

### ISSUE THREAD

**Issue by JustinGuese** [ConsenSys-archive/ganache#1503]
using the new alpha npm package with ubuntu 21.10

`npm install ganache@alpha --global`

npm 8.1.3
node 17.0.1

**running ganache in command line outputs**

```This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_linux_x64_102.node'
Falling back to a NodeJS implementation; performance may be degraded.


ganache v7.0.0-alpha.1 (@ganache/cli: 0.1.1-alpha.1, @ganache/core: 0.1.1-alpha.1)
```

**Comment by davidmurdoch** [comment]
Thanks for trying the alpha! This will be resolved in the next alpha release. It is safe to ignore this message.

**Comment by kitty-swap** [comment]
I am using ganache `v7.0.0-beta.2` with node `v12.14.1` and still got the same issue

**Comment by mrhouzlane** [comment]
I fixed this by doing `nvm use 16`

**Comment by davidmurdoch** [comment]
@mrhouzlane what version of Ganache and what version of Node did it not work on for you? Also, what operating system?

**Comment by mrhouzlane** [comment]
With `node v18.4.0`  I have the warning : Error: Cannot find module './uws_darwin_x64_108.node'
Falling back to a NodeJS implementation; performance may be degraded. 

But with `node v16.15.0` I don't have the warning. 

Ganache : `ganache v7.4.0 (@ganache/cli: 0.5.0, @ganache/core: 0.5.0)`

Using **macOS Monterey.**

**Comment by jymartineau** [comment]
@JustinGuese looks like this is still an issue, unfortunately... 

This version of µWS is not compatible with your Node.js build:

```
Error: Cannot find module '../binaries/uws_darwin_x64_115.node'
Require stack:
- /usr/local/lib/node_modules/truffle/node_modules/ganache/node_modules/@trufflesuite/uws-js-unofficial/src/uws.js
- /usr/local/lib/node_modules/truffle/node_modules/ganache/dist/node/core.js
- /usr/local/lib/node_modules/truffle/build/migrate.bundled.js
- /usr/local/lib/node_modules/truffle/node_modules/original-require/index.js
- /usr/local/lib/node_modules/truffle/build/cli.bundled.js
Falling back to a NodeJS implementation; performance may be degraded.
My development environment:

Truffle v5.9.4 (core: 5.9.4)
Ganache v7.8.0
Solidity v0.5.16 (solc-js)
Node v18.16.0
Web3.js v1.10.0
```

**Comment by muhammadfaisal02** [comment]
C:\Users\user\OneDrive\Desktop\Turffal code>truffle migrate
This version of µWS is not compatible with your Node.js build:

Error: The specified module could not be found.
\\?\C:\Users\user\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\@trufflesuite\uws-js-unofficial\binaries\uws_win32_x64_108.node
Falling back to a NodeJS implementation; performance may be degraded.

**Comment by davidmurdoch** [comment]
This will be fixed (again) in the next release as we drop node 14 and support node 20

**Comment by jobodev** [comment]
has this issue been fixed? I'm getting the same issue as well @davidmurdoch

**Comment by davidmurdoch** [comment]
what version of ganache and what version of node?

**Comment by jobodev** [comment]
v18.15.0
v18.17.0
v20.3.1

tested these node versions on ganache ^7.9.0 

error:

Error: Cannot find module '../binaries/uws_linux_x64_115.node'

**Comment by davidmurdoch** [comment]
Use the latest version 7.9.1

**Comment by jobodev** [comment]
thank you sir this worked :D
