### ISSUE TITLE
Calling eth_getLogs ends with an unhandled EIP155-related error

### ISSUE THREAD

**Issue by gabmontes** [ConsenSys-archive/ganache#910]
## Expected Behavior

When using `ganache-core` to programmatically fork the mainnet Ethereum chain and querying it for logs, any past/existing events should be retrieved as if the request to the Ethereum client the fork was created from.

## Current Behavior

The process ends up crashing with and unhandled promise rejection error:

```
(node:47221) UnhandledPromiseRejectionWarning: Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
```

## Steps to Reproduce (for bugs)

Run the following code:

```js
const ganache = require("ganache-core"); // @2.13.2
const Web3 = require("web3"); // @1.3.6

const httpProvider = new Web3.providers.HttpProvider(process.env.NODE_URL);
const forkProvider = ganache.provider({ fork: httpProvider });
const web3 = new Web3(forkProvider);

web3.eth.getPastLogs(
  {
    fromBlock: 12563800,
    toBlock: 12563810,
    topics: [
      // ERC-20 Approve event signature
      "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
      // A random owner address
      "0x000000000000000000000000f403c135812408bfbe8713b5a23a04b3d48aae31",
    ],
  },
  console.log
);
```

It will throw the following:

```
(node:47221) UnhandledPromiseRejectionWarning: Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
    at Transaction._validateV (./node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:370:13)
    at Transaction.set [as v] (./node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:387:16)
    at ./node_modules/ganache-core/lib/utils/transaction.js:116:23
    at Array.forEach (<anonymous>)
    at initData (./node_modules/ganache-core/lib/utils/transaction.js:110:18)
    at new Transaction (./node_modules/ganache-core/lib/utils/transaction.js:168:5)
    at Function.fromJSON (./node_modules/ganache-core/lib/utils/transaction.js:228:16)
    at ./node_modules/ganache-core/lib/forking/forked_blockchain.js:388:21
    at Array.forEach (<anonymous>)
    at Object.callback (./node_modules/ganache-core/lib/forking/forked_blockchain.js:386:31)
    at sendTxCallback (./node_modules/ganache-core/node_modules/web3-core-method/src/index.js:664:29)
    at onJsonrpcResult (./node_modules/ganache-core/node_modules/web3-core-requestmanager/src/index.js:179:9)
    at ./node_modules/ganache-core/lib/forking/forked_blockchain.js:136:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Note:

Digging a bit into the code, it looks like it is trying to replay the transactions in those blocks and when processing `0xe3bfbc0d881037378ede46078de1539066c0dbff4641ae379740aebd715721f0` at block 12563806, it fails validating the EIP-155 `v` value of `0` inside `ethereumjs-tx`.

So what may be happening is that this transaction was created with an non-EIP155 code/lib/wallet and `ethereumjs-tx` does not properly handle it.

## Context

This problem was seen while testing an app that relies on events to be logged, then processed. So alternatives have to be considered like testing the app in a live testnet or using other tools to fork the chain.

## Your Environment

* Version used: 2.13.2
* NodeJS Version: 12.x, 14.x
* Operating System and version: macOS 11.4
* Link to your project or repro gist: https://gist.github.com/gabmontes/440c533a03aa5f6749a308081b969311
* I intend to submit a pull request to fix this issue: [ ]

**Comment by KevinVitale** [comment]
Running into this issue with a graph-node locally deployed, connected to ganache (both v6.12.1 & v6.12.2).

```
Listening on 0.0.0.0:9545
web3_clientVersion
eth_getBlockByNumber
net_version
eth_getBlockByNumber
eth_getBlockByHash
eth_getBlockByHash
(node:1) UnhandledPromiseRejectionWarning: Error: Incompatible EIP155-based V 1 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
    at e._validateV (/app/ganache-core.docker.cli.js:42:94692)
    at e.set [as v] (/app/ganache-core.docker.cli.js:42:95123)
    at /app/ganache-core.docker.cli.js:12:125244
    at Array.forEach (<anonymous>)
    at /app/ganache-core.docker.cli.js:12:125135
    at new e (/app/ganache-core.docker.cli.js:12:125449)
    at Function.fromJSON (/app/ganache-core.docker.cli.js:12:126104)
    at /app/ganache-core.docker.cli.js:55:2315806
    at Array.forEach (<anonymous>)
    at Object.callback (/app/ganache-core.docker.cli.js:55:2315761)
    at f (/app/ganache-core.docker.cli.js:4:170132)
    at a (/app/ganache-core.docker.cli.js:55:2328023)
    at /app/ganache-core.docker.cli.js:55:2312254
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by cds-amal** [comment]
Hi @gabmontes, It is strange that EIP155 is relevant in this issue. We'll be looking into this. In the meantime, could you try setting your `chainId` manually to match that of the http provider fork at startup ? For example if you provider is mainnet, you chainId would be 1
```
const forkProvider = ganache.provider({ fork: httpProvider, _chainIdRpc: 1 });
```

if that doesn't work try adding `_chainId: 1` as well. We will try to reproduce this as well.

**Comment by gabmontes** [comment]
@cds-amal thanks for replying but I don't think that will work.

The problem is that some transactions existing in the chain have invalid v values and when replied within an eth_getLogs call, the mentioned error is thrown.

**Comment by davidmurdoch** [comment]
@gabmontes Looks like ganache is validating data from that it receives from the `fork` when it really shouldn't be, or at least it should be using different hardfork rules, depending on the context on the transaction it is validating. This will likely be fixed in the upcoming Ganache v7 release. You can try an internal preview of this release by first uninstalling ganache-cli/ganache-core and installing ganache@internal instead (`npm install ganache@internal` for library use or `npm install --global ganache@internal` for global use).

**Comment by DayBr3ak** [comment]
@davidmurdoch could you give an example? What you describe installs `    Ganache CLI v0.1.1-internal.1341 (ganache-core: 0.1.1-internal.1341)` and it does not solve the problem

**Comment by davidmurdoch** [comment]
@DayBr3ak can you try `npm install -g ganache@canary` and let me know if you still get the error?

**Comment by DayBr3ak** [comment]
It does work with that package thanks.

For anybody needing this, also launch ganache with `--miner.legacyInstamine true --miner.vmErrorsOnRPCResponse true`
or you'll wonder why things are not working

**Comment by davidmurdoch** [comment]
@DayBr3ak I'm impressed that you found those flags to switch back to to v6 behavior on your own since I haven't published the documentation or list of breaking changes yet!

The new default mode brings ganache in line with real nodes, but we do lose the immediate error feedback. I suspect we'll learn quickly that users will need some other mechanism for error feedback once the alpha version is released and announced this week.

You are the first to comment on this new default and I'd love to read your thoughts on ways you'd like us to surface these errors while maintaining alignment with real node behavior.

**Comment by DayBr3ak** [comment]
Honestly, I saw the commit you made in your 7.0 branch with the breaking changes.

I'm super new with all the ganache tools so I don't exactly know what I'm doing, but when I do, I'll be sure to give some feedback. I'm actually surprised ganache was not working like real nodes. That just proves I really don't know what I'm doing.

Thanks for the help

**Comment by tcoulter** [comment]
I got around this issue while using 6.12.2 by forking from a pre-EIP 1559 block (see the @ sign at the end of the fork URL; `10499400` is the block right before the fork)
```
ganache-cli -v --chainId 1 -i 1 --fork https://mainnet.infura.io/v3/<INFURA_KEY>@10499400
```

This will prevent Ganache 6.12.2 from processing transactions that it doesn't support.

Note that this may not work for you if your app needs more recent data. Fortunately for my use case forking from `10499400` was just fine.

**Comment by bgausden** [comment]
> I got around this issue while using 6.12.2 by forking from a pre-EIP 1559 block (see the @ sign at the end of the fork URL; `10499400` is the block right before the fork)
> 
> ```
> ganache-cli -v --chainId 1 -i 1 --fork https://mainnet.infura.io/v3/<INFURA_KEY>@10499400
> ```
> 
> This will prevent Ganache 6.12.2 from processing transactions that it doesn't support.
> 
> Note that this may not work for you if your app needs more recent data. Fortunately for my use case forking from `10499400` was just fine.

I'm having no luck with running graph-node (master branch) against a fork of mainnet from a Chainstack archive node. Was there anything else you could think of that makes it work for you?

```
Forked Chain
==================
Location:       https://xxx:yyy@nd-310-395-892.p2pify.com
Block:          10499400
Network ID:     1
Time:           Thu Oct 21 2021 18:00:04 GMT+0800 (Hong Kong Standard Time)
Max Cache Size: 1073741824 bytes

Listening on 127.0.0.1:8545
eth_getBlockByNumber
eth_getBlockByHash
eth_getBlockByHash
Error: Incompatible EIP155-based V 1 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
    at e._validateV (C:\Users\barryga\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:42:36890)
```

**Comment by davidmurdoch** [comment]
@bgausden Can you try with the alpha version of ganache? To install you need to run `npm uninstall ganache-cli -g` then `npm install ganache@alpha -g` You want to enable legacy mode with the following flags `--miner.legacyInstamine true --miner.vmErrorsOnRPCResponse true`

**Comment by bgausden** [comment]
> @bgausden Can you try with the alpha version of ganache? To install you need to run `npm uninstall ganache-cli -g` then `npm install ganache@alpha -g` You want to enable legacy mode with the following flags `--miner.legacyInstamine true --miner.vmErrorsOnRPCResponse true`

```
ganache-cli --version
This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_win32_x64_93.node'
Falling back to a NodeJS implementation; performance may be degraded.


ganache v7.0.0-alpha.1 (@ganache/cli: 0.1.1-alpha.1, @ganache/core: 0.1.1-alpha.1)
```
```
ganache-cli.cmd --fork https://"vibrant-stonebraker:strict-pull-maker-parole-possum-acid"@nd-310-395-892.p2pify.com --miner.legacyInstamine true --miner.vmErrorsOnRPCResponse true
This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_win32_x64_93.node'
Falling back to a NodeJS implementation; performance may be degraded.


Unknown argument: miner.vmErrorsOnRPCResponse
```

**Comment by davidmurdoch** [comment]
@bgausden Ah, sorry, I mixed up the argument namespace. Please try with `--chain.vmErrorsOnRPCResponse`.

p.s., If you use Node.js 12 or 14 the µWS warning will go away.

**Comment by haltman-at** [comment]
Closing this, as it should be fixed in Ganache 7.  If there's still an issue, feel free to file a new one!
